# 1D Cycle / Path Adjacency Matrix Generator (No Spin) [1]

In [1]:
#Importing necessary package
import numpy as np

#Defining the cycle adjacency matrix as a function of n
def cycle_adjacency_matrix(n):
    # Initializing an n x n matrix with zeros
    matrix = [[0] * n for _ in range(n)]
    # Setting the values for the diagonal
    for i in range(n):
        matrix[i][i] = 0
    # Setting the values for the upper and lower diagonals
    for i in range(n):
        matrix[i][(i + 1) % n] = 1
        matrix[i][(i - 1) % n] = 1
    return matrix

#Defining the path adjacency matrix as a function of n
def path_adjacency_matrix(n):
    #Initializing an n x n matrix with zeros
    matrix = [[0] * n for _ in range(n)]
    #Setting the values for the diagonal
    for i in range(n):
        matrix[i][i] = 0
    #Setting the values for the upper and lower diagonals
    for i in range(n):
        matrix[i][(i + 1) % n] = 1
        matrix[i][(i - 1) % n] = 1
    #Setting the path matrix apart from the cycle matrix
    matrix[n - 1][0] = 0
    matrix[0][n - 1] = 0
    return matrix

#Obtaining the number of nodes
n_1 = int(input("Enter the number of nodes: "))

#Obtaining the choice of cycle or path matrix
n_2 = int(input("Enter 0 for cycle, 1 for path: "))

#Repeating the choice if an invalid option is entered
while (n_2 != 0 and n_2 != 1):
    n_2 = int(input("Enter 0 for cycle, 1 for path: "))
    
#Generating the corresponding matrix
if (n_2 == 0):
    matrix = cycle_adjacency_matrix(n_1)
if (n_2 == 1):
    matrix = path_adjacency_matrix(n_1)
    
#Printing the matrix
print("The corresponding matrix: ")
for row in matrix:
    print(row)

#Finding the eigenvectors and eigenvalues, note that the eigenvectors are read vertically
eigenvalues, eigenvectors = np.linalg.eig(matrix)

#Printing the results
print("Eigenvalues: ")
print(eigenvalues)
print("Eigenvectors: ")
print(eigenvectors)

Enter the number of nodes: 3
Enter 0 for cycle, 1 for path: 0
The corresponding matrix: 
[0, 1, 1]
[1, 0, 1]
[1, 1, 0]
Eigenvalues: 
[-1.  2. -1.]
Eigenvectors: 
[[-0.81649658  0.57735027 -0.09265789]
 [ 0.40824829  0.57735027 -0.65620994]
 [ 0.40824829  0.57735027  0.74886783]]


# 2D Cycle / Path Adjacency Matrix Generator (No Spin) [2]

In [2]:
#Importing necessary package
import numpy as np

#Gobalizing necessary variables
global temp_up, temp_down, temp_left, temp_right, temp_center, temp_jump, lattice

#Defining the cycle matrix as a function of n
def cycle_matrix(n):
    # Initializing an n x n matrix with zeros
    matrix = [[0] * n for _ in range(n)]
    #Setting up the lattice
    lattice_no = int(n ** 0.5)
    lattice = [[j + 1 + lattice_no * i for j in range(lattice_no)] for i in range(lattice_no)]
    #Setting the values
    for i in range(lattice_no):
        for j in range(lattice_no):
            temp_center = lattice[i][j] - 1
            if (j <= lattice_no - 2):
                temp_right = lattice[i][j + 1] - 1
                matrix[temp_center][temp_right] = 1
                matrix[temp_right][temp_center] = 1
            if (j >= 1):
                temp_left = lattice[i][j - 1] - 1
                matrix[temp_center][temp_left] = 1
                matrix[temp_left][temp_center] = 1
            if (i >= 1):
                temp_up = lattice[i - 1][j] - 1
                matrix[temp_center][temp_up] = 1
                matrix[temp_up][temp_center] = 1
            if (i <= lattice_no - 2):
                temp_down = lattice[i + 1][j] - 1
                matrix[temp_center][temp_down] = 1
                matrix[temp_down][temp_center] = 1
            if (j == 0 or j == lattice_no - 1):
                temp_jump = lattice[i][lattice_no - 1] - 1
                matrix[temp_center][temp_jump] = 1
                matrix[temp_jump][temp_center] = 1
            if (i == 0 or i == lattice_no - 1):
                temp_jump = lattice[lattice_no - 1][j] - 1
                matrix[temp_center][temp_jump] = 1
                matrix[temp_jump][temp_center] = 1
    for i in range(n):
        matrix[i][i] = 0
    return matrix, lattice

def path_matrix(n):  
    # Initializing an n x n matrix with zeros
    matrix = [[0] * n for _ in range(n)]
    #Setting up the lattice
    lattice_no = int(n ** 0.5)
    lattice = [[j + 1 + lattice_no * i for j in range(lattice_no)] for i in range(lattice_no)]
    #Setting the values
    for i in range(lattice_no):
        for j in range(lattice_no):
            temp_center = lattice[i][j] - 1
            if (j <= lattice_no - 2):
                temp_right = lattice[i][j + 1] - 1
                matrix[temp_center][temp_right] = 1
                matrix[temp_right][temp_center] = 1
            if (j >= 1):
                temp_left = lattice[i][j - 1] - 1
                matrix[temp_center][temp_left] = 1
                matrix[temp_left][temp_center] = 1
            if (i >= 1):
                temp_up = lattice[i - 1][j] - 1
                matrix[temp_center][temp_up] = 1
                matrix[temp_up][temp_center] = 1
            if (i <= lattice_no - 2):
                temp_down = lattice[i + 1][j] - 1
                matrix[temp_center][temp_down] = 1
                matrix[temp_down][temp_center] = 1
    for i in range(n):
        matrix[i][i] = 0
    return matrix, lattice

#Obtaining the number of nodes
n_1 = float(input("Enter the number of nodes (please enter a number which is a cube of an integer): "))

#Making sure the input is valid
while (n_1 <= 1 or (n_1 ** 0.5) % 1 != 0):
    n_1 = float(input("Enter the number of nodes (please enter a number which is a cube of an integer): "))
n_1 = int(n_1)

#Obtaining the choice of cycle or path matrix
n_2 = int(input("Enter 0 for cycle, 1 for path: "))

#Making sure the input is valid
while (n_2 != 0 and n_2 != 1):
    n_2 = int(input("Enter 0 for cycle, 1 for path: "))

#Generating the corresponding matrix
if (n_2 == 0):
    matrix, lattice = cycle_matrix(n_1)
if (n_2 == 1):
    matrix, lattice = path_matrix(n_1)

#Printing the matrix
print("The lattice: ")
for row in lattice:
    print(row)
print("The corresponding matrix: ")
for row in matrix:
    print(row)

#Finding the eigenvectors and eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(matrix)

#Printing the results, note that the eigenvectors are read vertically
print("Eigenvalues: ")
print(eigenvalues)
print("Eigenvectors: ")
print(eigenvectors)

Enter the number of nodes (please enter a number which is a cube of an integer): 9
Enter 0 for cycle, 1 for path: 0
The lattice: 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
The corresponding matrix: 
[0, 1, 1, 1, 0, 0, 1, 0, 0]
[1, 0, 1, 0, 1, 0, 0, 1, 0]
[1, 1, 0, 0, 0, 1, 0, 0, 1]
[1, 0, 0, 0, 1, 1, 1, 0, 0]
[0, 1, 0, 1, 0, 1, 0, 1, 0]
[0, 0, 1, 1, 1, 0, 0, 0, 1]
[1, 0, 0, 1, 0, 0, 0, 1, 1]
[0, 1, 0, 0, 1, 0, 1, 0, 1]
[0, 0, 1, 0, 0, 1, 1, 1, 0]
Eigenvalues: 
[-2.  1.  4.  1. -2.  1. -2. -2.  1.]
Eigenvectors: 
[[ 0.66666667 -0.66666667 -0.33333333  0.11324429 -0.24595211  0.0090808
  -0.03474412  0.04458823 -0.00405038]
 [-0.33333333 -0.16666667 -0.33333333 -0.53493029 -0.41364672  0.02226828
   0.08808924 -0.0808107   0.22633531]
 [-0.33333333 -0.16666667 -0.33333333 -0.37400418  0.65959883 -0.12961424
  -0.05334512  0.03622247 -0.46641618]
 [-0.33333333 -0.16666667 -0.33333333  0.51108938  0.12297605  0.45668828
   0.40567488 -0.08066776 -0.07495955]
 [ 0.16666667  0.33333333 -0.33333333 -0.13

# 1D Cycle / Path Matrix Generator (No Change of Spin Direction Allowed) [3]

In [3]:
#Importing necessary package
import numpy as np

#Defining the cycle adjacency matrix as a function of n
def oneD_cycle_adjacency_matrix(n):
    #Initializing an n x n matrix with zeros
    matrix = [[0] * n for _ in range(n)]
    #Setting the values for the diagonal
    for i in range(n):
        matrix[i][i] = 0
    #Setting the values for the upper and lower diagonals
    for i in range(n):
        matrix[i][(i + 2) % n] = 1
        matrix[i][(i - 2) % n] = 1
    return matrix

#There are only a few differences between the cycle and path function. I could have used an if-branch to combine the two functions, which is done in later parts.
#Defining the path adjacency matrix as a function of n
def oneD_path_adjacency_matrix(n):
    #Initializing an n x n matrix with zeros
    matrix = [[0] * n for _ in range(n)]
    #Setting the values for the diagonal
    for i in range(n):
        matrix[i][i] = 0
    #Setting the values for the upper and lower diagonals
    for i in range(n):
        matrix[i][(i + 2) % n] = 1
        matrix[i][(i - 2) % n] = 1
    if (n * 0.5 != 2):
        matrix[0][n - 2] = 0
        matrix[n - 2][0] = 0
        matrix[1][n - 1] = 0
        matrix[n - 1][1] = 0
    return matrix

#Obtaining the number of nodes
n_1 = int(input("Enter the number of nodes: "))
n_1 = n_1 * 2

#Obtaining the choice of cycle or path matrix
n_2 = int(input("Enter 0 for cycle, 1 for path: "))

#Repeating the choice if an invalid option is entered
while (n_2 != 0 and n_2 != 1):
    n_2 = int(input("Enter 0 for cycle, 1 for path: "))
    
#Generating the corresponding matrix
if (n_2 == 0):
    matrix = oneD_cycle_adjacency_matrix(n_1)
if (n_2 == 1):
    matrix = oneD_path_adjacency_matrix(n_1)

#Printing the matrix
print("The corresponding matrix: ")
for row in matrix:
    print(row)
    
#Finding the eigenvectors and eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(matrix)

#Printing the results
print("Eigenvalues: ")
print(eigenvalues)
print("Eigenvectors: ")
print(eigenvectors)

Enter the number of nodes: 3
Enter 0 for cycle, 1 for path: 0
The corresponding matrix: 
[0, 0, 1, 0, 1, 0]
[0, 0, 0, 1, 0, 1]
[1, 0, 0, 0, 1, 0]
[0, 1, 0, 0, 0, 1]
[1, 0, 1, 0, 0, 0]
[0, 1, 0, 1, 0, 0]
Eigenvalues: 
[-1.  2. -1.  2. -1. -1.]
Eigenvectors: 
[[-8.16496581e-01  5.77350269e-01  1.35118573e-01 -5.42329534e-02
   1.05586286e-02  2.80303678e-02]
 [ 4.27325041e-17 -1.20471054e-16 -8.05238870e-01 -5.74797460e-01
  -8.80937767e-02 -1.67046921e-01]
 [ 4.08248290e-01  5.77350269e-01 -6.75592866e-02 -5.42329534e-02
   4.30989513e-01 -3.07128688e-01]
 [ 0.00000000e+00  5.35130709e-17  4.02619435e-01 -5.74797460e-01
  -5.07102376e-01 -5.43027968e-01]
 [ 4.08248290e-01  5.77350269e-01 -6.75592866e-02 -5.42329534e-02
  -4.41548141e-01  2.79098320e-01]
 [ 0.00000000e+00  5.79947082e-17  4.02619435e-01 -5.74797460e-01
   5.95196153e-01  7.10074889e-01]]


# 2D Cycle / Path Matrix Generator (No Change of Spin Direction Allowed) [4]

In [4]:
#Importing necessary package
import numpy as np

#Globalizing necessary variables
global temp_up, temp_down, temp_left, temp_right, temp_center, temp_jump, lattice, matrix

#Defining the cycle adjacency matrix as a function of n
def twoD_cycle_adjacency_matrix(n):
    #Setting up the lattice
    lattice_no = int(n ** 0.5)
    lattice = [[j + 1 + lattice_no * i for j in range(lattice_no)] for i in range(lattice_no)]
    #Setting up the matrix
    matrix_no = n * 2
    matrix = [[0] * matrix_no for _ in range(matrix_no)]
    #Setting the values
    for i in range(lattice_no):
        for j in range(lattice_no):
            #temp_center is a site in the lattice. The if-branches are checking the possibility of tunnelling into neighbouring sites
            temp_center = lattice[i][j] - 1
            temp_center = temp_center * 2
            if (j <= lattice_no - 2):
                temp_right = lattice[i][j + 1] - 1
                temp_right = temp_right * 2
                matrix[temp_center][temp_right] = 1
                matrix[temp_right][temp_center] = 1
                matrix[temp_center + 1][temp_right + 1] = 1
                matrix[temp_right + 1][temp_center + 1] = 1
            if (j >= 2):
                temp_left = lattice[i][j - 1] - 1
                temp_left = temp_left * 2
                matrix[temp_center][temp_left] = 1
                matrix[temp_left][temp_center] = 1
                matrix[temp_center + 1][temp_left + 1] = 1
                matrix[temp_left + 1][temp_center + 1] = 1
            if (i >= 1):
                temp_up = lattice[i - 1][j] - 1
                temp_up = temp_up * 2
                matrix[temp_center][temp_up] = 1
                matrix[temp_up][temp_center] = 1
                matrix[temp_center + 1][temp_up + 1] = 1
                matrix[temp_up + 1][temp_center + 1] = 1
            if (i <= lattice_no - 2):
                temp_down = lattice[i + 1][j] - 1
                temp_down = temp_down * 2
                matrix[temp_center][temp_down] = 1
                matrix[temp_down][temp_center] = 1
                matrix[temp_center + 1][temp_down + 1] = 1
                matrix[temp_down + 1][temp_center + 1] = 1
            if (j == 0 or j == lattice_no - 1):
                temp_jump = lattice[i][lattice_no - 1] - 1
                temp_jump = temp_jump * 2
                matrix[temp_center][temp_jump] = 1
                matrix[temp_jump][temp_center] = 1
                matrix[temp_center + 1][temp_jump + 1] = 1
                matrix[temp_jump + 1][temp_center + 1] = 1
            if (i == 0 or i == lattice_no - 1):
                temp_jump = lattice[lattice_no - 1][j] - 1
                temp_jump = temp_jump * 2
                matrix[temp_center][temp_jump] = 1
                matrix[temp_jump][temp_center] = 1
                matrix[temp_center + 1][temp_jump + 1] = 1
                matrix[temp_jump + 1][temp_center + 1] = 1
    for i in range(matrix_no):
        matrix[i][i] = 0
    return matrix, lattice

#Defining the path adjacency matrix as a function of n
def twoD_path_adjacency_matrix(n):
    #Setting up the lattice
    lattice_no = int(n ** 0.5)
    lattice = [[j + 1 + lattice_no * i for j in range(lattice_no)] for i in range(lattice_no)]
    #Setting up the matrix
    matrix_no = n * 2
    matrix = [[0] * matrix_no for _ in range(matrix_no)]
    #Setting the values
    for i in range(lattice_no):
        for j in range(lattice_no):
            #temp_center is a site in the lattice. The if-branches are checking the possibility of tunnelling into neighbouring sites
            temp_center = lattice[i][j] - 1
            temp_center = temp_center * 2
            if (j <= lattice_no - 2):
                temp_right = lattice[i][j + 1] - 1
                temp_right = temp_right * 2
                matrix[temp_center][temp_right] = 1
                matrix[temp_right][temp_center] = 1
                matrix[temp_center + 1][temp_right + 1] = 1
                matrix[temp_right + 1][temp_center + 1] = 1
            if (j >= 2):
                temp_left = lattice[i][j - 1] - 1
                temp_left = temp_left * 2
                matrix[temp_center][temp_left] = 1
                matrix[temp_left][temp_center] = 1
                matrix[temp_center + 1][temp_left + 1] = 1
                matrix[temp_left + 1][temp_center + 1] = 1
            if (i >= 1):
                temp_up = lattice[i - 1][j] - 1
                temp_up = temp_up * 2
                matrix[temp_center][temp_up] = 1
                matrix[temp_up][temp_center] = 1
                matrix[temp_center + 1][temp_up + 1] = 1
                matrix[temp_up + 1][temp_center + 1] = 1
            if (i <= lattice_no - 2):
                temp_down = lattice[i + 1][j] - 1
                temp_down = temp_down * 2
                matrix[temp_center][temp_down] = 1
                matrix[temp_down][temp_center] = 1
                matrix[temp_center + 1][temp_down + 1] = 1
                matrix[temp_down + 1][temp_center + 1] = 1
    for i in range(matrix_no):
        matrix[i][i] = 0
    return matrix, lattice

#Obtaining the number of nodes
n_1 = float(input("Enter the number of nodes (please enter a number which is a cube of an integer): "))

#Making sure the input is valid
while (n_1 <= 1 or (n_1 ** 0.5) % 1 != 0):
    n_1 = float(input("Enter the number of nodes (please enter a nubmer which is a cube of an integer): "))
n_1 = int(n_1)

#Obtaining the choice of cycle or path matrix
n_2 = int(input("Enter 0 for cycle, 1 for path: "))

#Making sure the input is valid
while (n_2 != 0 and n_2 != 1):
    n_2 = int(input("Enter 0 for cycle, 1 for path: "))

#Generating the corresponding matrix
if (n_2 == 0):
    matrix, lattice = twoD_cycle_adjacency_matrix(n_1)
if (n_2 == 1):
    matrix, lattice = twoD_path_adjacency_matrix(n_1)

#Printing the matrices
print("The lattice: ")
for row in lattice:
    print(row)
print("The corresponding matrix: ")
for row in matrix:
    print(row)
    
#Finding the eigenvectors and eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(matrix)

#Printing the results
print("Eigenvalues: ")
print(eigenvalues)
print("Eigenvectors: ")
print(eigenvectors)

Enter the number of nodes (please enter a number which is a cube of an integer): 9
Enter 0 for cycle, 1 for path: 0
The lattice: 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
The corresponding matrix: 
[0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]
[0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0]
[1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0]
[0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]
[0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]
[0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1]
[0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 

# 1D Cycle / Path Adjacency Matrix Generator (Change of Spin Direction Allowed) [5]

In [5]:
#Importing the necessary package
import numpy as np

#Defining the cycle adjacency matrix as a function of n
def oneD_cycle_adjacency_matrix(n):
    #Initializing an n x n matrix with zeros
    matrix = [[0] * n for _ in range(n)]
    #Setting the values for the diagonal
    for i in range(n):
        matrix[i][i] = 0
    #Setting the values for the upper and lower diagonals
    for i in range(n):
        matrix[i][(i + 2) % n] = 1
        matrix[i][(i - 2) % n] = 1
    for i in range(n):
        for j in range(n):
            if (i % 2 == 0):
                matrix[i][j] = matrix[i][j] + matrix[i + 1][j]
            else:
                matrix[i][j] = matrix[i][j] + matrix[i - 1][j]
    for i in range(n):
        for j in range(n):
            if (matrix[i][j] > 1):
                matrix[i][j] = 1
    return matrix

#Defining the cycle adjacency matrix as a function of n
def oneD_path_adjacency_matrix(n):
    #Initializing an n x n matrix with zeros
    matrix = [[0] * n for _ in range(n)]
    #Setting the values for the diagonal
    for i in range(n):
        matrix[i][i] = 0
    #Setting the values for the upper and lower diagonals
    for i in range(n):
        matrix[i][(i + 2) % n] = 1
        matrix[i][(i - 2) % n] = 1
    if (n * 0.5 != 2):
        matrix[0][n - 2] = 0
        matrix[n - 2][0] = 0
        matrix[1][n - 1] = 0
        matrix[n - 1][1] = 0
    for i in range(n):
        for j in range(n):
            if (i % 2 == 0):
                matrix[i][j] = matrix[i][j] + matrix[i + 1][j]
            else:
                matrix[i][j] = matrix[i][j] + matrix[i - 1][j]
    for i in range(n):
        for j in range(n):
            if (matrix[i][j] > 1):
                matrix[i][j] = 1
    return matrix

#Obtaining the number of nodes
n_1 = int(input("Enter the number of nodes: "))
n_1 = n_1 * 2

#Obtaining the choice of cycle or path matrix
n_2 = int(input("Enter 0 for cycle, 1 for path: "))

#Repeating the choice if an invalid option is entered
while (n_2 != 0 and n_2 != 1):
    n_2 = int(input("Enter 0 for cycle, 1 for path: "))
    
#Generating the corresponding matrix
if (n_2 == 0):
    matrix = oneD_cycle_adjacency_matrix(n_1)
if (n_2 == 1):
    matrix = oneD_path_adjacency_matrix(n_1)


print("1D: ")
for row in matrix:
    print(row)
    
#Finding the eigenvectors and eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(matrix)

#Printing the results
print("Eigenvalues: ")
print(eigenvalues)
print("Eigenvectors: ")
print(eigenvectors)

Enter the number of nodes: 3
Enter 0 for cycle, 1 for path: 0
1D: 
[0, 0, 1, 1, 1, 1]
[0, 0, 1, 1, 1, 1]
[1, 1, 0, 0, 1, 1]
[1, 1, 0, 0, 1, 1]
[1, 1, 1, 1, 0, 0]
[1, 1, 1, 1, 0, 0]
Eigenvalues: 
[ 4.00000000e+00 -1.04671836e-16 -2.00000000e+00 -2.00000000e+00
 -3.64550591e-17  9.24446373e-33]
Eigenvectors: 
[[-4.08248290e-01 -7.07106781e-01  5.77350269e-01  1.47694255e-01
   2.51904285e-16  1.05545255e-16]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01  1.47694255e-01
  -2.19285227e-16 -1.61056406e-16]
 [-4.08248290e-01  1.62732113e-17 -2.88675135e-01  4.09515889e-01
  -5.52202296e-01  1.75470265e-16]
 [-4.08248290e-01  1.62732113e-17 -2.88675135e-01  4.09515889e-01
   5.52202296e-01 -2.27462030e-16]
 [-4.08248290e-01  1.62732113e-17 -2.88675135e-01 -5.57210144e-01
  -4.41670267e-01 -7.07106781e-01]
 [-4.08248290e-01  1.62732113e-17 -2.88675135e-01 -5.57210144e-01
   4.41670267e-01  7.07106781e-01]]


# 2D Cycle / Path Adjacency Matrix Generator (Change of Spin Direction Allowed) [6]

In [6]:
#Globalizing necessary variables
global temp_up, temp_down, temp_left, temp_right, temp_center, temp_jump, lattice, matrix

#Defining the cycle adjacency matrix as a function of n
def twoD_cycle_adjacency_matrix(n):
    #Setting up the lattice
    lattice_no = int(n_1 ** 0.5)
    lattice = [[j + 1 + lattice_no * i for j in range(lattice_no)] for i in range(lattice_no)]
    #Setting up the matrix
    matrix_no = n * 2
    matrix = [[0] * matrix_no for _ in range(matrix_no)]
    #Setting the values
    for i in range(lattice_no):
        for j in range(lattice_no):
            #temp_center is a site in the lattice. The if-branches are checking the possibility of tunnelling into neighbouring sites
            temp_center = lattice[i][j] - 1
            temp_center = temp_center * 2
            if (j <= lattice_no - 2):
                temp_right = lattice[i][j + 1] - 1
                temp_right = temp_right * 2
                matrix[temp_center][temp_right] = 1
                matrix[temp_right][temp_center] = 1
                matrix[temp_center + 1][temp_right + 1] = 1
                matrix[temp_right + 1][temp_center + 1] = 1
            if (j >= 2):
                temp_left = lattice[i][j - 1] - 1
                temp_left = temp_left * 2
                matrix[temp_center][temp_left] = 1
                matrix[temp_left][temp_center] = 1
                matrix[temp_center + 1][temp_left + 1] = 1
                matrix[temp_left + 1][temp_center + 1] = 1
            if (i >= 1):
                temp_up = lattice[i - 1][j] - 1
                temp_up = temp_up * 2
                matrix[temp_center][temp_up] = 1
                matrix[temp_up][temp_center] = 1
                matrix[temp_center + 1][temp_up + 1] = 1
                matrix[temp_up + 1][temp_center + 1] = 1
            if (i <= lattice_no - 2):
                temp_down = lattice[i + 1][j] - 1
                temp_down = temp_down * 2
                matrix[temp_center][temp_down] = 1
                matrix[temp_down][temp_center] = 1
                matrix[temp_center + 1][temp_down + 1] = 1
                matrix[temp_down + 1][temp_center + 1] = 1
            if (j == 0 or j == lattice_no - 1):
                temp_jump = lattice[i][lattice_no - 1] - 1
                temp_jump = temp_jump * 2
                matrix[temp_center][temp_jump] = 1
                matrix[temp_jump][temp_center] = 1
                matrix[temp_center + 1][temp_jump + 1] = 1
                matrix[temp_jump + 1][temp_center + 1] = 1
            if (i == 0 or i == lattice_no - 1):
                temp_jump = lattice[lattice_no - 1][j] - 1
                temp_jump = temp_jump * 2
                matrix[temp_center][temp_jump] = 1
                matrix[temp_jump][temp_center] = 1
                matrix[temp_center + 1][temp_jump + 1] = 1
                matrix[temp_jump + 1][temp_center + 1] = 1
    for i in range(matrix_no):
        matrix[i][i] = 0
    for i in range(matrix_no):
        for j in range(matrix_no):
            if (i % 2 == 0):
                matrix[i][j] = matrix[i][j] + matrix[i + 1][j]
            else:
                matrix[i][j] = matrix[i][j] + matrix[i - 1][j]
    for i in range(matrix_no):
        for j in range(matrix_no):
            if (matrix[i][j] > 1):
                matrix[i][j] = 1
    return matrix, lattice

#Defining the path adjacency matrix as a function of n
def twoD_path_adjacency_matrix(n):
    #Setting up the lattice
    lattice_no = int(n_1 ** 0.5)
    lattice = [[j + 1 + lattice_no * i for j in range(lattice_no)] for i in range(lattice_no)]
    #Setting up the matrix
    matrix_no = n * 2
    matrix = [[0] * matrix_no for _ in range(matrix_no)]
    #Setting the values
    for i in range(lattice_no):
        for j in range(lattice_no):
            #temp_center is a site in the lattice. The if-branches are checking the possibility of tunnelling into neighbouring sites
            temp_center = lattice[i][j] - 1
            temp_center = temp_center * 2
            if (j <= lattice_no - 2):
                temp_right = lattice[i][j + 1] - 1
                temp_right = temp_right * 2
                matrix[temp_center][temp_right] = 1
                matrix[temp_right][temp_center] = 1
                matrix[temp_center + 1][temp_right + 1] = 1
                matrix[temp_right + 1][temp_center + 1] = 1
            if (j >= 2):
                temp_left = lattice[i][j - 1] - 1
                temp_left = temp_left * 2
                matrix[temp_center][temp_left] = 1
                matrix[temp_left][temp_center] = 1
                matrix[temp_center + 1][temp_left + 1] = 1
                matrix[temp_left + 1][temp_center + 1] = 1
            if (i >= 1):
                temp_up = lattice[i - 1][j] - 1
                temp_up = temp_up * 2
                matrix[temp_center][temp_up] = 1
                matrix[temp_up][temp_center] = 1
                matrix[temp_center + 1][temp_up + 1] = 1
                matrix[temp_up + 1][temp_center + 1] = 1
            if (i <= lattice_no - 2):
                temp_down = lattice[i + 1][j] - 1
                temp_down = temp_down * 2
                matrix[temp_center][temp_down] = 1
                matrix[temp_down][temp_center] = 1
                matrix[temp_center + 1][temp_down + 1] = 1
                matrix[temp_down + 1][temp_center + 1] = 1
    for i in range(matrix_no):
        matrix[i][i] = 0
    for i in range(matrix_no):
        for j in range(matrix_no):
            if (i % 2 == 0):
                matrix[i][j] = matrix[i][j] + matrix[i + 1][j]
            else:
                matrix[i][j] = matrix[i][j] + matrix[i - 1][j]
    for i in range(matrix_no):
        for j in range(matrix_no):
            if (matrix[i][j] > 1):
                matrix[i][j] = 1
    return matrix, lattice

#Obtaining the number of nodes
n_1 = float(input("Enter the number of nodes (please enter a number which is a cube of an integer): "))

#Making sure the input is valid
while (n_1 <= 1 or (n_1 ** 0.5) % 1 != 0):
    n_1 = float(input("Enter the number of nodes (please enter a nubmer which is a cube of an integer): "))
n_1 = int(n_1)

#Obtaining the choice of cycle or path matrix
n_2 = int(input("Enter 0 for cycle, 1 for path: "))

#Making sure the input is valid
while (n_2 != 0 and n_2 != 1):
    n_2 = int(input("Enter 0 for cycle, 1 for path: "))

#Generating the corresponding matrix
if (n_2 == 0):
    matrix, lattice = twoD_cycle_adjacency_matrix(n_1)
if (n_2 == 1):
    matrix, lattice = twoD_path_adjacency_matrix(n_1)

#Printing the matrix
print("The lattice: ")
for row in lattice:
    print(row)
print("The corresponding matrix: ")
for row in matrix:
    print(row)
    
#Finding the eigenvectors and eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(matrix)

#Printing the results
print("Eigenvalues: ")
print(eigenvalues)
print("Eigenvectors: ")
print(eigenvectors)

Enter the number of nodes (please enter a number which is a cube of an integer): 9
Enter 0 for cycle, 1 for path: 0
The lattice: 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
The corresponding matrix: 
[0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1]
[1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
[0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0]
[0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0]
[0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1]
[0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1]
[1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
[1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
[0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 

# 2D Cycle / Path Adjacency Matrix Generator (t, t_z, m_z, t_so) [7]

In [9]:
#Importing necessary package
import numpy as np

#Globalizing necessary variables
global J, tz, mz, Lx, Ly, tso

#Defining the adjacency matrices as a function of n
def twoD_adjacency_matrix(n):
    #Creating the different parts of Hamiltonian
    matrix_up_up = np.zeros((Lx * Ly, Lx * Ly))
    matrix_down_down = np.zeros((Lx * Ly, Lx * Ly))
    matrix_up_down = np.zeros((Lx * Ly, Lx * Ly), dtype = complex)
    matrix_down_up = np.zeros((Lx * Ly, Lx * Ly), dtype = complex)
    for jx_1 in range(Lx):
        for jy_1 in range(Ly):
            #js_1 = 0 (Spin up); js_1 = 1 (Spin down)
            for js_1 in range(2):
                for jx_2 in range(Lx):
                    for jy_2 in range(Ly):
                        #js_2 = 0 (Spin up); js_2 = 1 (Spin down)
                        for js_2 in range(2):
                            #This is a new approach. In the codes above, I checked the indices to determine the tunnelling possibility.
                            #In this approach, I check the distances between two sites to determine the tunnelling possibility.
                            distance = ((jx_2 - jx_1) ** 2 + (jy_2 - jy_1) ** 2) ** 0.5
                            #Adding J and tz to the matrix
                            if (distance == 1 and js_1 == js_2):
                                if (jx_2 - jx_1 == 1 or jy_2 - jy_1 == 1):
                                    jj = (jy_1 * Lx + jx_1)
                                    jj_new = (jy_2 * Lx + jx_2)
                                    if (js_1 == 0):
                                        matrix_up_up[jj_new][jj] = -J + tz
                                    if (js_1 == 1):
                                        matrix_down_down[jj_new][jj] = -J - tz
                            #Periodic boundary condition
                            if (n == 0):
                                #Tunnelling in the x-direction
                                if (jx_1 == Lx - 1 and js_1 == js_2):
                                    jj = (jy_1 * Lx + jx_1)
                                    jj_new = (jy_1 * Lx + 0)
                                    if (js_1 == 0):
                                        matrix_up_up[jj_new][jj] = -J + tz
                                    if (js_1 == 1):
                                        matrix_down_down[jj_new][jj] = -J - tz
                                #Tunnelling in the y-direction
                                if (jy_1 == Ly - 1 and js_1 == js_2):
                                    jj = (jy_1 * Lx + jx_1)
                                    jj_new = (0 * Lx + jx_1)
                                    if (js_1 == 0):
                                        matrix_up_up[jj_new][jj] = -J + tz
                                    if (js_1 == 1):
                                        matrix_down_down[jj_new][jj] = -J - tz
                            #Adding mz to the matrix
                            if (js_1 == 0):
                                jj = (jy_1 * Lx + jx_1)
                                matrix_up_up[jj][jj] = 0.5 * mz
                            if (js_1 == 1):
                                jj = (jy_1 * Lx + jx_1)
                                matrix_down_down[jj][jj] = -0.5 * mz
                            #Adding real tso to the matrix
                            if (distance == 1 and js_1 != js_2):
                                if (jx_2 - jx_1 == 1 and js_1 != js_2):
                                    jj = (jy_1 * Lx + jx_1)
                                    jj_new = (jy_2 * Lx + jx_2)
                                    if (js_1 == 0):
                                        matrix_up_down[jj_new][jj] = tso
                                    if (js_1 == 1):
                                        matrix_down_up[jj_new][jj] = tso
                                if (jy_2 - jy_1 == 1 and js_1 != js_2):
                                    jj =(jy_1 * Lx + jx_1)
                                    jj_new = (jy_2 * Lx + jx_2)
                                    if (js_1 == 0): 
                                        matrix_up_down[jj_new][jj] = -tso
                                    if (js_1 == 1):
                                        matrix_down_up[jj_new][jj] = -tso
                            #Periodic boundary condition
                            if (n == 0):
                                #Tunnelling in the x-direction
                                if (jx_1 == Lx - 1 and js_1 != js_2):
                                    jj = (jy_1 * Lx + jx_1)
                                    jj_new = (jy_1 * Lx + 0)
                                    if (js_1 == 0):
                                        matrix_up_down[jj_new][jj] = tso 
                                    if (js_1 == 1):
                                        matrix_down_up[jj_new][jj] = tso
                                #Tunnelling in the y-direction
                                if (jy_1 == Ly - 1 and js_1 != js_2):
                                    if (js_1 != js_2):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = (0 * Lx + jx_1)
                                        if (js_1 == 0):
                                            matrix_up_down[jj_new][jj] = -tso 
                                        if (js_1 == 1):
                                            matrix_down_up[jj_new][jj] = -tso
                            #Adding imaginary tso to the matrix
                            if (distance == 2 ** 0.5 and js_1 != js_2):
                                if (js_1 == 0):
                                    if ((jy_2 - jy_1) // (jx_2 - jx_1) > 0 and jy_2 - jy_1 == 1 and jx_2 - jx_1 == 1):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = (jy_2 * Lx + jx_2)
                                        matrix_up_down[jj_new][jj] = complex(0, tso)
                                    if ((jy_2 - jy_1) // (jx_2 - jx_1) < 0 and jy_2 - jy_1 == -1 and jx_2 - jx_1 == 1):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = (jy_2 * Lx + jx_2)
                                        matrix_up_down[jj_new][jj] = complex(0, -tso)
                                if (js_1 == 1):
                                    if ((jy_2 - jy_1) // (jx_2 - jx_1) > 0 and jy_2 - jy_1 == 1 and jx_2 - jx_1 == 1):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = (jy_2 * Lx + jx_2)
                                        matrix_down_up[jj_new][jj] = complex(0, -tso)
                                    if ((jy_2 - jy_1) // (jx_2 - jx_1) < 0 and jy_2 - jy_1 == -1 and jx_2 - jx_1 == 1):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = (jy_2 * Lx + jx_2)
                                        matrix_down_up[jj_new][jj] = complex(0, tso)
                            #Periodic boundary condition
                            if (n == 0):
                                #Upper right corner
                                if (jx_1 == Lx - 1 and jy_1 == Ly - 1 and js_1 != js_2):
                                    if (js_1 == 0):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = (0 * Lx + 0)
                                        matrix_up_down[jj_new][jj] = complex(0, tso)
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((jy_1 - 1) * Lx + 0)
                                        matrix_up_down[jj_new][jj] = complex(0, -tso)
                                    if (js_1 == 1):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = (0 * Lx + 0)
                                        matrix_down_up[jj_new][jj] = complex(0, -tso)
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((jy_1 - 1) * Lx + 0)
                                        matrix_down_up[jj_new][jj] = complex(0, tso)
                                #Bottom right corner
                                if (jx_1 == Lx - 1 and jy_1 == 0 and js_1 != js_2):
                                    if (js_1 == 0):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((jy_1 + 1) * Lx + 0)
                                        matrix_up_down[jj_new][jj] = complex(0, tso)
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((Ly - 1) * Lx + 0)
                                        matrix_up_down[jj_new][jj] = complex(0, -tso)
                                    if (js_1 == 1):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((jy_1 + 1) * Lx + 0)
                                        matrix_down_up[jj_new][jj] = complex(0, -tso)
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((Ly - 1) * Lx + 0)
                                        matrix_down_up[jj_new][jj] = complex(0, tso)
                                #The borders except the above two corners
                                #Bottom
                                if (jx_1 != Lx - 1 and jy_1 == 0 and js_1 != js_2):
                                    if (js_1 == 0):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((Ly - 1) * Lx + (jx_1 + 1))
                                        matrix_up_down[jj_new][jj] = complex(0, -tso)
                                    if (js_1 == 1):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((Ly - 1) * Lx + (jx_1 + 1))
                                        matrix_down_up[jj_new][jj] = complex(0, tso)
                                #Top
                                if (jx_1 != Lx - 1 and jy_1 == Ly - 1 and js_1 != js_2):
                                    if (js_1 == 0):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = (0 * Lx + (jx_1 + 1))
                                        matrix_up_down[jj_new][jj] = complex(0, tso)
                                    if (js_1 == 1):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = (0 * Lx + (jx_1 + 1))
                                        matrix_down_up[jj_new][jj] = complex(0, -tso)
                                #Right
                                if (jy_1 != 0 and jy_1 != Ly - 1 and jx_1 == Lx - 1 and js_1 != js_2):
                                    if (js_1 == 0):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((jy_1 + 1) * Lx + 0)
                                        matrix_up_down[jj_new][jj] = complex(0, tso)
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((jy_1 - 1) * Lx + 0)
                                        matrix_up_down[jj_new][jj] = complex(0, -tso)
                                    if (js_1 == 1):
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((jy_1 + 1) * Lx + 0)
                                        matrix_down_up[jj_new][jj] = complex(0, -tso)
                                        jj = (jy_1 * Lx + jx_1)
                                        jj_new = ((jy_1 - 1) * Lx + 0)
                                        matrix_down_up[jj_new][jj] = complex(0, tso)
    #Adding the corresponding Hamiltonian conjugates to the matrices
    matrix_up_up = matrix_up_up + np.transpose(matrix_up_up)
    matrix_down_down = matrix_down_down + np.transpose(matrix_down_down)
    matrix_up_down = matrix_up_down + np.transpose(matrix_up_down)
    matrix_down_up = matrix_down_up + np.transpose(matrix_down_up)
    return matrix_up_up, matrix_down_down, matrix_up_down, matrix_down_up

#Obtaining the number of vertices
Lx = int(input("Enter the value of Lx: "))
Ly = int(input("Enter the value of Ly: "))

#Obtaining the choice of cycle or path matrix
n_1 = int(input("Enter 0 for cycle, 1 for path: "))

#Making sure the input is valid
while (n_1 != 0 and n_1 != 1):
    n_1 = int(input("Enter 0 for cycle, 1 for path: "))

J = float(input("Enter the value of t: "))
tz = float(input("Enter the value of tz: "))
mz = float(input("Enter the value of mz: "))
tso = float(input("Enter the value of tso: "))
    
#Generating the corresponding matrices
matrix_up_up, matrix_down_down, matrix_up_down, matrix_down_up = twoD_adjacency_matrix(n_1)

#Printing the matrix
print("matrix_up_up: ")
for row in matrix_up_up:
    print(row)
print("matrix_down_down: ")
for row in matrix_down_down:
    print(row)
print("matrix_up_down: ")
for row in matrix_up_down:
    print(row)
print("matrix_down_up: ")
for row in matrix_down_up:
    print(row)
hamiltonian_1 = np.hstack((matrix_up_up, matrix_up_down))
hamiltonian_2 = np.hstack((matrix_down_up, matrix_down_down))
hamiltonian_1p = np.vstack((hamiltonian_1, hamiltonian_2))
print("Hamiltonian: ")
for row in hamiltonian_1p:
    print(row)

#Finding the eigenvectors and eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(hamiltonian_1p)

#Printing the results, note that the eigenvectors are read vertically
print("Eigenvalues: ")
print(eigenvalues)
print("Eigenvectors: ")
print(eigenvectors)

Enter the value of Lx: 3
Enter the value of Ly: 3
Enter 0 for cycle, 1 for path: 0
Enter the value of t: 1
Enter the value of tz: 0.5
Enter the value of mz: 0.1
Enter the value of tso: 1
matrix_up_up: 
[ 0.1 -0.5 -0.5 -0.5  0.   0.  -0.5  0.   0. ]
[-0.5  0.1 -0.5  0.  -0.5  0.   0.  -0.5  0. ]
[-0.5 -0.5  0.1  0.   0.  -0.5  0.   0.  -0.5]
[-0.5  0.   0.   0.1 -0.5 -0.5 -0.5  0.   0. ]
[ 0.  -0.5  0.  -0.5  0.1 -0.5  0.  -0.5  0. ]
[ 0.   0.  -0.5 -0.5 -0.5  0.1  0.   0.  -0.5]
[-0.5  0.   0.  -0.5  0.   0.   0.1 -0.5 -0.5]
[ 0.  -0.5  0.   0.  -0.5  0.  -0.5  0.1 -0.5]
[ 0.   0.  -0.5  0.   0.  -0.5 -0.5 -0.5  0.1]
matrix_down_down: 
[-0.1 -1.5 -1.5 -1.5  0.   0.  -1.5  0.   0. ]
[-1.5 -0.1 -1.5  0.  -1.5  0.   0.  -1.5  0. ]
[-1.5 -1.5 -0.1  0.   0.  -1.5  0.   0.  -1.5]
[-1.5  0.   0.  -0.1 -1.5 -1.5 -1.5  0.   0. ]
[ 0.  -1.5  0.  -1.5 -0.1 -1.5  0.  -1.5  0. ]
[ 0.   0.  -1.5 -1.5 -1.5 -0.1  0.   0.  -1.5]
[-1.5  0.   0.  -1.5  0.   0.  -0.1 -1.5 -1.5]
[ 0.  -1.5  0.   0.  -1.5  

# 2D 2-Particle Cycle / Path Adjacency Matrix Generator (t, t_z, m_z, t_so) [8]

In [8]:
#Importing necessary packages
import numpy as np
from itertools import combinations_with_replacement

#Calculating the Cartesian product of the 1-particle Hamiltonian with itself
hamiltonian_2p = np.kron(hamiltonian_1p, np.identity(2 * Lx * Ly)) + np.kron(np.identity(2 * Lx * Ly), hamiltonian_1p)

#Creating the matrix Q
Q = np.zeros((int((2 * Lx * Ly) ** 2), int((2 * Lx * Ly) * (2 * Lx * Ly + 1) * 0.5)), dtype = complex)

#Creating the necessary arrays
state = []
state_combination = []
site = []

#Filling in the state array
for i in range(2 * Lx * Ly):
    state.append(i)

#Filling in the state_combination array, which corresponds to the column of Q. In this array, only ascending order of combinations are allowed
for comb in combinations_with_replacement(state, 2):
    real_part = comb[0]
    imaginary_part = comb[1]
    state_combination.append(complex(comb[0], comb[1]))

#Filling in the site array, which corresponds to the row of Q
for i in range(2 * Lx * Ly):
    for j in range(2 * Lx * Ly):
        site.append(complex(i, j))

#Filling in Q
for i in range(len(state_combination)):
    state_temporary1 = state_combination[i].real
    state_temporary2 = state_combination[i].imag
    if (state_temporary1 == state_temporary2):
        same = True
    if (state_temporary1 != state_temporary2):
        same = False
    for j in range(len(site)):
        site_temporary1 = site[j].real
        site_temporary2 = site[j].imag
        if (state_temporary1 == site_temporary1 and state_temporary2 == site_temporary2) or (state_temporary1 == site_temporary2 and state_temporary2 == site_temporary1):
            if (same == True):
                Q[j][i] = 1
            if (same == False):
                Q[j][i] = 1 / (2 ** 0.5)

#Calculating the final matrix
final_matrix = np.dot(Q.T, hamiltonian_2p)
final_final_matrix = np.dot(final_matrix, Q)

#Printing the final matrix
print("The corresponding matrix: ")
for row in final_final_matrix:
    print(row)
#Finding the eigenvectors and eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(final_final_matrix)

#Printing the results, note that the eigenvectors are read vertically
print("Eigenvalues: ")
print(eigenvalues)  

The corresponding matrix: 
[ 0.2       +0.j          2.12132034+0.j          2.12132034+0.j
  2.12132034+0.j          0.        +0.j          0.        +0.j
  2.12132034+0.j          0.        +0.j          0.        +0.j
  0.        +0.j          1.41421356+0.j          1.41421356+0.j
 -1.41421356+0.j          0.        +1.41421356j  0.        -1.41421356j
 -1.41421356+0.j          0.        -1.41421356j  0.        +1.41421356j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j
  0.        +0.j          0.        +0.j       

[ 0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  1.5       +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  1.5       +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  2.12132034+0.j
  0.2       +0.j  1.5       +0.j  0.        +0.j  1.5       +0.j
  0.        +0.j  0.        +1.j -1.        +0.j  0.        -1.j
  1.        +0.j  0.     

[ 0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j -1.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +1.j  0.        +0.j
  0.        +0.j  1.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        -1.j  0.        +0.j
  0.        +0.j  1.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
  0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
 -1.        +0.j  0.     

Eigenvalues: 
[ 12.2       +7.39724300e-18j -10.26418391-1.11757212e-17j
  10.15941171+7.67689942e-17j  10.15941171+4.85722573e-16j
  10.15941171+9.55046589e-16j   8.11882342-7.20351214e-17j
   8.        -1.87574196e-17j  10.15941171+9.48898869e-16j
   8.11882342+1.61324155e-16j   8.11882342-9.00321484e-16j
   7.23209195-2.60551389e-17j   7.23209195+2.42887168e-16j
   7.23209195-1.68644260e-18j -10.26418391+1.22554308e-18j
  -7.19150366-4.76293961e-17j  -7.19150366-4.79312228e-16j
  -7.19150366+7.21211285e-16j  -7.19150366-1.05997025e-15j
 -10.26418391+4.02455846e-16j -10.26418391+1.66533454e-15j
 -10.26418391+4.71844785e-16j -10.26418391+1.35828848e-15j
 -10.26418391+3.90919935e-15j  -7.19150366-4.45529457e-16j
   5.95941171+1.73099144e-16j   3.8       +2.11272829e-16j
   5.95941171-4.97697707e-16j  -3.23209195-1.67240286e-16j
  -3.23209195+3.25135539e-16j   4.04058829+1.94289684e-16j
   4.04058829-2.08166817e-16j   4.04058829-5.39282161e-16j
   0.96790805-5.20417040e-17j   0.96790805